name: Run analyze and tests

on: pull_request

jobs:
  analyze-and-test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
