name: iOS

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter doctor -v
      - run: flutter build ios --release --no-codesign