name: Notify

on:
  workflow_run:
    workflows: [ pages-build-deployment ]
    types: [ completed ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on success
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Action status:  ${{ github.event.workflow_run.conclusion}}
            
            Workflow event: ${{ github.event.workflow_run}}
            
            ${{ github.actor }} created commit:
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
