name: Web

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter doctor -v
      - uses: bluefireteam/flutter-gh-pages@v8
        with:
          baseHref: /clock/